#!/bin/bash

# Install a grunt plugin and save to devDependencies
gi () {
	npm install --save-dev grunt-"$@"
}

# Install a grunt-contrib plugin and save to devDependencies
gci () {
	npm install --save-dev grunt-contrib-"$@"
}
