#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles by Hans Christian Reinl (http://drublic.de/)

Additional software to install

Browsers:
	Firefox
	Firefox Nightly
	Google Chrome
	Google Chrome Canary

Development:
	ImageOptim
	Sublime Text
	Slowy
	VirtualBox

Other:
	1Password
	Divvy
	Dropbox
	Flux
	LimeChat

EOT

}
